# Generated by Django 4.1.1 on 2023-01-24 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.CharField(choices=[('Fast food', 'FAST_FOOD'), ('Casual dining', 'CASUAL_DINING'), ('Fast Casual', 'FAST_CASUAL'), ('Contemporary', 'CONTEMPORARY'), ('Café', 'CAFE'), ('Pizzeria', 'PIZZERIA')], default='Casual dining', max_length=20)),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField()),
                ('opening_hours', models.TextField()),
                ('price', models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], default=1)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
