# Generated by Django 4.1.1 on 2023-01-25 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.CharField(choices=[(1, 'FAST_FOOD'), (2, 'CASUAL_DINING'), (3, 'FAST_CASUAL'), (4, 'CONTEMPORARY'), (5, 'CAFE'), (6, 'PIZZERIA')], default='Casual dining', max_length=20)),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('opening_hours', models.TextField()),
                ('price', models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$')], null=True)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
