# Generated by Django 4.1.1 on 2023-01-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating_average',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
