# Generated by Django 4.1.1 on 2023-01-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_rating_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating_average',
        ),
    ]
