# Generated by Django 4.1.1 on 2023-01-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'FAST_FOOD'), (2, 'CASUAL_DINING'), (3, 'FAST_CASUAL'), (4, 'CONTEMPORARY'), (5, 'CAFE'), (6, 'PIZZERIA')], default=2),
        ),
    ]
